/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package habitatinterface;

import java.util.HashSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tiago
 */
public class AdicionarTarefa extends javax.swing.JDialog {
    HashSet<String> addedVol;
    /**
     * Creates new form AdicionarTarefa
     */
    public AdicionarTarefa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        addedVol = new HashSet<String>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfNome = new javax.swing.JTextField();
        jtfDataF = new javax.swing.JFormattedTextField();
        jtfDataIn = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox();
        jScrollPane11 = new javax.swing.JScrollPane();
        jtPesquisa = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtVoluntariosTarefa = new javax.swing.JTable();
        jbAddVoluntario = new javax.swing.JButton();
        jbRemoveVoluntário = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jbSubmitTarefa = new javax.swing.JButton();
        jLabel91 = new javax.swing.JLabel();
        searchVolunteersField = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        volunteerProjectFilter = new javax.swing.JCheckBox();
        volunteerEventFilter = new javax.swing.JCheckBox();
        searchVolunteersButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtfDataF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jtfDataF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataFActionPerformed(evt);
            }
        });

        jtfDataIn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel8.setText("Data Final(Prevista):");

        jLabel7.setText("Data de Início:");

        jLabel4.setText("Nome:");

        jLabel9.setText("Estado:");

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Em Curso", "Atrasada", "Completada" }));

        jtPesquisa.setAutoCreateRowSorter(true);
        jtPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Equipa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPesquisa.getTableHeader().setReorderingAllowed(false);
        jScrollPane11.setViewportView(jtPesquisa);

        jtVoluntariosTarefa.setAutoCreateRowSorter(true);
        jtVoluntariosTarefa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "NrHoras"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVoluntariosTarefa.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(jtVoluntariosTarefa);

        jbAddVoluntario.setText("<");
        jbAddVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddVoluntarioActionPerformed(evt);
            }
        });

        jbRemoveVoluntário.setText(">");
        jbRemoveVoluntário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoveVoluntárioActionPerformed(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel64.setText("Participantes");

        jbSubmitTarefa.setText("Submeter");
        jbSubmitTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubmitTarefaActionPerformed(evt);
            }
        });

        jLabel91.setText("Pesquisa:");

        jLabel45.setText("Filtros");

        volunteerProjectFilter.setBackground(new java.awt.Color(255, 255, 255));
        volunteerProjectFilter.setText("Trabalhou em pelo menos um projeto");
        volunteerProjectFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volunteerProjectFilterActionPerformed(evt);
            }
        });

        volunteerEventFilter.setBackground(new java.awt.Color(255, 255, 255));
        volunteerEventFilter.setText("Participou em pelo menos um evento");

        searchVolunteersButton.setText("Pesquisar");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfDataIn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfDataF, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel64)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbAddVoluntario)
                                            .addComponent(jbRemoveVoluntário))))))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSubmitTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel91)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchVolunteersField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(volunteerProjectFilter)
                                    .addComponent(volunteerEventFilter))
                                .addGap(0, 151, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchVolunteersButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel91)
                            .addComponent(searchVolunteersField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(searchVolunteersButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volunteerProjectFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volunteerEventFilter)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                        .addComponent(jbSubmitTarefa)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtfDataIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDataF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jbAddVoluntario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbRemoveVoluntário))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addComponent(jSeparator1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDataFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataFActionPerformed

    private void jbSubmitTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubmitTarefaActionPerformed
        //Criar objeto Tarefa, mas não pôr já na Base de Dados
        this.dispose();
    }//GEN-LAST:event_jbSubmitTarefaActionPerformed

    private void jbAddVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddVoluntarioActionPerformed
        Integer rowID;
        if(( rowID = jtPesquisa.getSelectedRow()) >= 0){
            if(!this.addedVol.contains((String) jtPesquisa.getValueAt( jtPesquisa.getSelectedRow(), 0 ) )){
                ((DefaultTableModel)jtVoluntariosTarefa.getModel()).addRow(new Object[]{jtPesquisa.getValueAt( jtPesquisa.getSelectedRow(), 0 ), "", ""});
                addedVol.add((String) jtPesquisa.getValueAt( jtPesquisa.getSelectedRow(), 0 ) );
            }
        }
    }//GEN-LAST:event_jbAddVoluntarioActionPerformed

    private void jbRemoveVoluntárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoveVoluntárioActionPerformed
        Integer rowID;
        if(( rowID = jtVoluntariosTarefa.getSelectedRow()) >= 0){
            addedVol.remove((String) jtVoluntariosTarefa.getValueAt( jtVoluntariosTarefa.getSelectedRow(), 0 ) );
            ((DefaultTableModel)jtVoluntariosTarefa.getModel()).removeRow(rowID);
        }
    }//GEN-LAST:event_jbRemoveVoluntárioActionPerformed

    private void volunteerProjectFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volunteerProjectFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volunteerProjectFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAddVoluntario;
    private javax.swing.JButton jbRemoveVoluntário;
    private javax.swing.JButton jbSubmitTarefa;
    private javax.swing.JComboBox jcbEstado;
    private javax.swing.JTable jtPesquisa;
    private javax.swing.JTable jtVoluntariosTarefa;
    private javax.swing.JFormattedTextField jtfDataF;
    private javax.swing.JFormattedTextField jtfDataIn;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JButton searchVolunteersButton;
    private javax.swing.JTextField searchVolunteersField;
    private javax.swing.JCheckBox volunteerEventFilter;
    private javax.swing.JCheckBox volunteerProjectFilter;
    // End of variables declaration//GEN-END:variables
}
