/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package habitat;

import controllers.ContactsController;
import controllers.ControllerFactory;
import controllers.DonorsController;
import data.DataException;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultCellEditor;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.Activity;
import models.Donor;

/**
 *
 * @author paulo
 */
public class AdicionarDoador extends javax.swing.JDialog {

    /**
     * Creates new form AdicionarDoador
     */
    public AdicionarDoador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addDonorContactsAddButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        addDonorContactsRemoveButton = new javax.swing.JButton();
        donorDesignation = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        addDonorContactsTable = new javax.swing.JTable();
        donorNIF = new javax.swing.JTextField();
        donorAddress = new javax.swing.JTextField();
        donorActivity = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cancelAddDonorButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cleanAddDonorButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SubmitAddDonorButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        donorNIB = new javax.swing.JTextField();
        donorType = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        donorNotes = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setTitle("Adicionar Doador");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Contactos:");

        jLabel5.setText("Tipo:");

        addDonorContactsAddButton.setText("+");
        addDonorContactsAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonorContactsAddButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Actividade:");

        addDonorContactsRemoveButton.setText("-");
        addDonorContactsRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonorContactsRemoveButtonActionPerformed(evt);
            }
        });

        donorDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorDesignationActionPerformed(evt);
            }
        });

        addDonorContactsTable.setAutoCreateRowSorter(true);
        addDonorContactsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Contacto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane15.setViewportView(addDonorContactsTable);
        if (addDonorContactsTable.getColumnModel().getColumnCount() > 0) {
            addDonorContactsTable.getColumnModel().getColumn(0).setCellEditor( new DefaultCellEditor(
                new javax.swing.JComboBox(
                    new javax.swing.DefaultComboBoxModel(
                        new String[] { "Telefone", "Telemóvel", "Email", "Fax" }))) );
    }

    donorActivity.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            donorActivityActionPerformed(evt);
        }
    });

    jLabel1.setText("Nome:");

    cancelAddDonorButton.setText("Cancelar");
    cancelAddDonorButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelAddDonorButtonActionPerformed(evt);
        }
    });

    jLabel2.setText("NIF:");

    cleanAddDonorButton.setText("Limpar");
    cleanAddDonorButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cleanAddDonorButtonActionPerformed(evt);
        }
    });

    jLabel3.setText("Morada:");

    SubmitAddDonorButton.setText("Submeter");
    SubmitAddDonorButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            SubmitAddDonorButtonActionPerformed(evt);
        }
    });

    jLabel4.setText("Observações:");

    jLabel8.setText("NIB:");

    donorNIB.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            donorNIBActionPerformed(evt);
        }
    });

    donorType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Individual", "Instituição" }));
    donorType.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            donorTypeActionPerformed(evt);
        }
    });

    donorNotes.setColumns(20);
    donorNotes.setLineWrap(true);
    donorNotes.setRows(5);
    donorNotes.setToolTipText("");
    donorNotes.setWrapStyleWord(true);
    jScrollPane2.setViewportView(donorNotes);
    donorNotes.setDocument(new JTextAreaLimit(500));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel7)
                .addComponent(jLabel6)
                .addComponent(jLabel5)
                .addComponent(jLabel4)
                .addComponent(jLabel3)
                .addComponent(jLabel2)
                .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(donorType, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(donorActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addDonorContactsAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addDonorContactsRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cancelAddDonorButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                            .addComponent(cleanAddDonorButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                            .addComponent(SubmitAddDonorButton))
                        .addComponent(donorDesignation, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(donorAddress, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(donorNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(donorNIB))
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGap(61, 61, 61))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(donorDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(donorNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8)
                .addComponent(donorNIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(donorAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(donorType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(donorActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(addDonorContactsAddButton)
                .addComponent(addDonorContactsRemoveButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cancelAddDonorButton)
                .addComponent(cleanAddDonorButton)
                .addComponent(SubmitAddDonorButton))
            .addGap(20, 20, 20))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDonorContactsAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonorContactsAddButtonActionPerformed
        ((DefaultTableModel)addDonorContactsTable.getModel()).addRow(new Object[]{"", "", ""});
    }//GEN-LAST:event_addDonorContactsAddButtonActionPerformed

    private void addDonorContactsRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonorContactsRemoveButtonActionPerformed
        int rowID;
        if(( rowID = addDonorContactsTable.getSelectedRow()) >= 0)
        ((DefaultTableModel)addDonorContactsTable.getModel()).removeRow(rowID);
    }//GEN-LAST:event_addDonorContactsRemoveButtonActionPerformed

    private void donorDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donorDesignationActionPerformed

    private void cancelAddDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddDonorButtonActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cancelAddDonorButtonActionPerformed

    private void cleanAddDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanAddDonorButtonActionPerformed
        donorAddress.setText("");
        donorDesignation.setText("");
        donorNIF.setText("");
        donorNotes.setText("");
    }//GEN-LAST:event_cleanAddDonorButtonActionPerformed

    public void setActivities() throws DataException{
        Collection<Activity> items = ControllerFactory.getActivityController().all();
        for( Activity a: items){
            donorActivity.addItem(a);
        }
    }
    
    private void SubmitAddDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitAddDonorButtonActionPerformed
        DonorsController dc = ControllerFactory.getDonorsController();
        ContactsController cc = ControllerFactory.getContactsController();
        
        try {           
            final Donor d = dc.save(new HashMap<String, Object>() {{
                put("name", donorDesignation.getText());
                put("address", donorAddress.getText());
                put("nif", donorNIF.getText());
                if (donorType.getSelectedItem().toString().equals("Doador"))
                    put("dType", true);
                else put("dType", false);
                put("activity", donorActivity.getSelectedItem().toString() );
                put("nib", donorNIB.getText());
                put("observations", donorNotes.getText());                
            }});
            
            final TableModel t = addDonorContactsTable.getModel();
            int totalContacts = t.getRowCount();
            List<Map<String, Object>> contacts = new ArrayList<>();
            
            for(int i = 0; i < totalContacts; i++) {
                final int i2 = i;
                contacts.add( new HashMap<String, Object>() {{
                    put("type", t.getValueAt(i2, 0).toString());
                    put("value", t.getValueAt(i2, 1).toString());
                    put("owner", d.getId() );
                    put("ownerType", "Doador");
                }});
            }
            
            cc.saveAll(contacts);
            
            
        } catch (DataException e) {
            // SHOW ERROR MESSAGE
        }
    }//GEN-LAST:event_SubmitAddDonorButtonActionPerformed

    private void donorActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorActivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donorActivityActionPerformed

    private void donorNIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorNIBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donorNIBActionPerformed

    private void donorTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donorTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitAddDonorButton;
    private javax.swing.JButton addDonorContactsAddButton;
    private javax.swing.JButton addDonorContactsRemoveButton;
    private javax.swing.JTable addDonorContactsTable;
    private javax.swing.JButton cancelAddDonorButton;
    private javax.swing.JButton cleanAddDonorButton;
    private javax.swing.JComboBox donorActivity;
    private javax.swing.JTextField donorAddress;
    private javax.swing.JTextField donorDesignation;
    private javax.swing.JTextField donorNIB;
    private javax.swing.JTextField donorNIF;
    private javax.swing.JTextArea donorNotes;
    private javax.swing.JComboBox donorType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
