/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package habitatinterface;

import java.awt.event.WindowEvent;
import javax.swing.DefaultCellEditor;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo
 */
public class AdicionarDoador extends javax.swing.JDialog {

    /**
     * Creates new form AdicionarDoador
     */
    public AdicionarDoador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addDonorContactsAddButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        addDonorContactsRemoveButton = new javax.swing.JButton();
        donorDesignation = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        addDonorContactsTable = new javax.swing.JTable();
        donorNIF = new javax.swing.JTextField();
        donorAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addDonorObservation = new javax.swing.JTextArea();
        donorType = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cancelAddDonorButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cleanAddDonorButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SubmitAddDonorButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setTitle("Adicionar Doador");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Contactos:");

        jLabel5.setText("Tipo:");

        addDonorContactsAddButton.setText("+");
        addDonorContactsAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonorContactsAddButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Actividade:");

        addDonorContactsRemoveButton.setText("-");
        addDonorContactsRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonorContactsRemoveButtonActionPerformed(evt);
            }
        });

        donorDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorDesignationActionPerformed(evt);
            }
        });

        addDonorContactsTable.setAutoCreateRowSorter(true);
        addDonorContactsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Tipo", "Contacto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane15.setViewportView(addDonorContactsTable);

        addDonorObservation.setEditable(true);

        addDonorObservation.setLineWrap(true);

        addDonorObservation.setToolTipText("");

        addDonorObservation.setWrapStyleWord(true);

        addDonorObservation.setDocument(new JTextAreaLimit(500));
        addDonorObservation.setColumns(20);
        addDonorObservation.setRows(5);
        jScrollPane1.setViewportView(addDonorObservation);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Designação:");

        cancelAddDonorButton.setText("Cancelar");
        cancelAddDonorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddDonorButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("NIF:");

        cleanAddDonorButton.setText("Limpar");
        cleanAddDonorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanAddDonorButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Morada:");

        SubmitAddDonorButton.setText("Submeter");

        jLabel4.setText("Observações:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(addDonorContactsAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addDonorContactsRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelAddDonorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cleanAddDonorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitAddDonorButton))
                    .addComponent(donorDesignation)
                    .addComponent(donorAddress)
                    .addComponent(donorType)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(donorNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(donorDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(donorNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(donorAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(donorType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDonorContactsAddButton)
                    .addComponent(addDonorContactsRemoveButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelAddDonorButton)
                    .addComponent(cleanAddDonorButton)
                    .addComponent(SubmitAddDonorButton))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDonorContactsAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonorContactsAddButtonActionPerformed
        ((DefaultTableModel)addDonorContactsTable.getModel()).addRow(new Object[]{"", "", ""});
    }//GEN-LAST:event_addDonorContactsAddButtonActionPerformed

    private void addDonorContactsRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonorContactsRemoveButtonActionPerformed
        int rowID;
        if(( rowID = addDonorContactsTable.getSelectedRow()) >= 0)
        ((DefaultTableModel)addDonorContactsTable.getModel()).removeRow(rowID);
    }//GEN-LAST:event_addDonorContactsRemoveButtonActionPerformed

    private void donorDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donorDesignationActionPerformed

    private void cancelAddDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddDonorButtonActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cancelAddDonorButtonActionPerformed

    private void cleanAddDonorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanAddDonorButtonActionPerformed
        donorAddress.setText("");
        donorDesignation.setText("");
        donorNIF.setText("");
        addDonorObservation.setText("");
        donorType.setText("");
    }//GEN-LAST:event_cleanAddDonorButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitAddDonorButton;
    private javax.swing.JButton addDonorContactsAddButton;
    private javax.swing.JButton addDonorContactsRemoveButton;
    private javax.swing.JTable addDonorContactsTable;
    private javax.swing.JTextArea addDonorObservation;
    private javax.swing.JButton cancelAddDonorButton;
    private javax.swing.JButton cleanAddDonorButton;
    private javax.swing.JTextField donorAddress;
    private javax.swing.JTextField donorDesignation;
    private javax.swing.JTextField donorNIF;
    private javax.swing.JTextField donorType;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
