-- MySQL Script generated by MySQL Workbench
-- 01/05/15 11:49:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Atividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Atividades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Atividades` (
  `id` INT NULL,
  `Designacao` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `id` INT NULL,
  `Atividade` INT NULL,
  `Designacao` VARCHAR(75) NULL,
  `NrContribuinte` INT NULL,
  `Contacto` VARCHAR(75) NULL,
  `Rua` VARCHAR(75) NULL,
  `Localidade` VARCHAR(50) NULL,
  `CodPostal` VARCHAR(60) NULL,
  `Telefone` VARCHAR(25) NULL,
  `Fax` VARCHAR(25) NULL,
  `eMail` VARCHAR(100) NULL,
  `NrProcesso` INT NULL,
  `VolumeNegocios` VARCHAR(60) NULL,
  `Observacoes` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Clientes_Atividades1_idx` (`Atividade` ASC),
  CONSTRAINT `fk_Clientes_Atividades1`
    FOREIGN KEY (`Atividade`)
    REFERENCES `mydb`.`Atividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionarios` (
  `id` INT NULL,
  `Nome` VARCHAR(75) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `Rua` VARCHAR(75) NULL,
  `Localidade` VARCHAR(50) NULL,
  `CodPostal` VARCHAR(60) NULL,
  `DataInicioServico` DATE NULL,
  `AnosServico` INT NULL,
  `Telefone1` VARCHAR(25) NULL,
  `Telefone2` VARCHAR(25) NULL,
  `eMail` VARCHAR(100) NULL,
  `Observacoes` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Processos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Processos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Processos` (
  `Nr` INT NULL,
  `Cliente` INT NULL,
  `DataProcesso` DATE NULL,
  `DataAprovacao` DATE NULL,
  `DataEncerramento` DATE NULL,
  `Descricao` TEXT NULL,
  `CustoMaterial` DECIMAL(15) NULL,
  `CustoEquipamento` DECIMAL(15) NULL,
  `CustoFinal` DECIMAL(15) NULL,
  `Designacao` VARCHAR(75) NULL,
  `Observacoes` TEXT NULL,
  `Processoscol` VARCHAR(45) NULL,
  `FuncionarioAbriu` INT NULL,
  `FuncionarioAprovou` INT NULL,
  `FuncionariosEncerrou` INT NULL,
  PRIMARY KEY (`Nr`),
  INDEX `fk_Processos_Clientes_idx` (`Cliente` ASC),
  INDEX `fk_Processos_Funcionarios1_idx` (`FuncionarioAbriu` ASC),
  INDEX `fk_Processos_Funcionarios2_idx` (`FuncionarioAprovou` ASC),
  INDEX `fk_Processos_Funcionarios3_idx` (`FuncionariosEncerrou` ASC),
  CONSTRAINT `fk_Processos_Clientes`
    FOREIGN KEY (`Cliente`)
    REFERENCES `mydb`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Processos_Funcionarios1`
    FOREIGN KEY (`FuncionarioAbriu`)
    REFERENCES `mydb`.`Funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Processos_Funcionarios2`
    FOREIGN KEY (`FuncionarioAprovou`)
    REFERENCES `mydb`.`Funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Processos_Funcionarios3`
    FOREIGN KEY (`FuncionariosEncerrou`)
    REFERENCES `mydb`.`Funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
